displayName: migmig Middleware by MohamadReza
type: middleware
iconPath: .assets/icon.png

import: github.com/mohamadrezamomeni/migmig

summary: "[Demo] Add Request Header"

testData:
  Headers:
    X-Demo: test
    X-URL: "{{URL}}"
